# Generated by Django 3.0 on 2024-11-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='addtocart/%Y/%m/%d')),
                ('price', models.IntegerField()),
                ('ordered', models.BooleanField()),
            ],
        ),
    ]
